
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THAI_WORKSPACE_ROOT
  - name: react-js
    command: |
      cd frontend-react-js
      npm i
  - name: xray-daemon
    command: |
      cd /workspace
      wget https://s3.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.deb
      sudo dpkg -i **.deb